all:
	javac-algs4 *.java

unit: all
	java-algs4 Percolation

inter2: all
	java-algs4 InteractivePercolationVisualizer 2

inter3: allc
	java-algs4 InteractivePercolationVisualizer 3

inter4: all
	java-algs4 InteractivePercolationVisualizer 4

inter5: allc
	java-algs4 InteractivePercolationVisualizer 5

clean:
	rm -v *class
